spring.application.name=Videira-Natural

server.port=${PORT:8080}

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.main.lazy-initialization=true
server.tomcat.threads.max=20

spring.flyway.enabled=false


# Em vez de 'update', use 'create' para gerar o dump completo
spring.jpa.hibernate.ddl-auto=create

# Adicione estas linhas para exportar o arquivo
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql
spring.jpa.show-sql=true

api.security.token.secret=chave-secreta-super-segura-videira-2026