spring.application.name=Videira-Natural

server.port=${PORT:8080}

### H2 Database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#POSTGRES
spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:19022/db_videira
spring.datasource.username=postgres
spring.datasource.password=hXJsRiQMKmUNaxDcethcUOZeKkQRviWJ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#INTEGRACAO MERCADO PAGO.
#mercadopago.point.device-id=PAX_A910__N950NCC804149944
#mercadopago.access.token=APP_USR-8722515787980770-100715-592f5fd18cf9604e2282fdfe5bc93882-3747971474

spring.main.lazy-initialization=true
server.tomcat.threads.max=20

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.org.hibernate.stat=ERROR
logging.level.org.springframework.core.env=DEBUG
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

gemini.api.key=${GEMINI_API_KEY}

api.security.token.secret=chave-secreta-super-segura-videira-2026