spring.application.name=Videira-Natural

server.port=${PORT:8080}

# Usa as variáveis que o Railway injeta no container
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false

# Garante que o Hibernate crie/atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true