spring.application.name=Videira-Natural

server.port=${PORT:8080}

## H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.main.lazy-initialization=true
server.tomcat.threads.max=20

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=chave-secreta-super-segura-videira-2026