spring.application.name=Videira-Natural
server.port=${PORT:8080}
spring.profiles.active=prod

# POSTGRES DE PRODUÇÃO (Pega direto da variável injetada pelo Railway)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.lazy-initialization=true
server.tomcat.threads.max=20

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.org.hibernate.stat=ERROR

api.security.token.secret=chave-secreta-super-segura-videira-2026